# COURSE: Master math by coding in Python
## SECTION: Algebra 1

#### https://www.udemy.com/course/math-with-python/?couponCode=MXC-DISC4ALL
#### INSTRUCTOR: sincxpress.com

Note about this code: Each video in this section of the course corresponds to a section of code below. Please note that this code roughly matches the code shown in the live recording, but is not exactly the same -- the variable names, order of lines, and parameters may be slightly different. 

In [1]:
# It's generally good practice to import all required modules at the top of the script!
import sympy as sym
import numpy as np
from IPython.display import display, Math

# VIDEO: Solving for x

In [2]:
x = sym.symbols('x')

# the expression we want to solve is 2x+4=9
expr = 2*x + 4 -9

sym.solve(expr,x)

[5/2]

In [5]:
solution = sym.solve(expr,x)
display('The solution to %s is %g' %(sym.latex(expr), solution[0]))

'The solution to 2 x - 5 is 2.5'

In [6]:
# make it look a bit nicer

sol = sym.solve(expr,x)

display('The solution to %s is %g'%(expr,sol[0]))

# or
display(Math('\\text{The solution to }%s\\text{ is x=}%g' %(sym.latex(expr),sol[0])))

'The solution to 2*x - 5 is 2.5'

<IPython.core.display.Math object>

In [5]:
# can input the equation directly into the solve function
x = sym.symbols('x')
sym.solve(x**2 - 4,x)

[-2, 2]

In [7]:
# notice the solution is stored as a list, with one solution per element
sol = sym.solve(x**2 - 4,x)

print( type(sol) )
print( len(sol) )
print(sol)

<class 'list'>
2
[-2, 2]


In [8]:
# we can print them all out:
for i in range(0,len(sol)):
    print('Solution #' + str(i+1) + ' is ' + str(sol[i]))


Solution #1 is -2
Solution #2 is 2


In [12]:
y = sym.symbols('y')

expr = x/4 - x*y + 5

print( "Solved for x: " + str(sym.solve(expr,x)[0]) )
print( "Solved for y: " + str(sym.solve(expr,y)) )

display(sym.solve(expr, x))
display(sym.solve(expr, y))


Solved for x: 20/(4*y - 1)
Solved for y: [(x + 20)/(4*x)]


[20/(4*y - 1)]

[(x + 20)/(4*x)]

### Exercises

In [2]:
import sympy as sym
from IPython.display import display, Math

In [26]:
# Ex1:
q = sym.symbols('q')
eq = (3*q) + (4/q) + 3 - (5*q) - (1/q) - 1

display(Math(sym.latex(sym.simplify(eq))))
display(Math('q=' + sym.latex(sym.solve(eq, q))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [25]:
# Ex2:
q = sym.symbols('q')
eq = 2*q + 3*(q**2) - (5 / q) - ( 4 / (q**3))
display(eq)

display(Math(sym.latex(sym.simplify(eq))))
display(Math(sym.latex(sym.cancel(eq))))
display(Math(sym.latex(sym.solve(eq))))

3*q**2 + 2*q - 5/q - 4/q**3

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [27]:
# Ex3: 
q = sym.symbols('q')
eq = (sym.sqrt(3) + sym.sqrt(15*q)) / (sym.sqrt(2) + sym.sqrt(10*q))
display(eq)
display(sym.simplify(eq))
display(eq.subs(q, 10))

(sqrt(15)*sqrt(q) + sqrt(3))/(sqrt(10)*sqrt(q) + sqrt(2))

sqrt(6)/2

(sqrt(3) + 5*sqrt(6))/(sqrt(2) + 10)

In [ ]:
# 1)
# simplify and solve for q
q = sym.symbols('q')
eq = 3*q + 4/q + 3 - 5*q - 1/q - 1

display(Math(sym.latex(eq.simplify()))) 
display(Math('q='+sym.latex(sym.solve(eq,q))))

In [ ]:
# 2)
eq = 2*q + 3*q**2 - 5/q - 4/q**3

display(Math(sym.latex(eq)))
display(Math(sym.latex(sym.simplify(eq))))
display(Math(sym.latex(sym.cancel(eq)))) # puts into p/q form with integer coefficients

In [ ]:
# 3)
# simplify this expression. confirm on your own using paper-and-pencil
expr = (sym.sqrt(3) + sym.sqrt(15)*q) / (sym.sqrt(2) + sym.sqrt(10)*q)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.simplify(expr))))

In [ ]:
sym.simplify( expr.subs(q,10) )

In [ ]:
expr.subs(q,10).evalf()

# VIDEO: Expanding terms

In [4]:
import sympy as sym
from IPython.display import display, Math

In [6]:
# define our terms
from sympy.abc import x

term1 = (4*x + 5)
term2 = x

print( term1*term2 )
print( sym.expand(term1*term2) )
print( Math(sym.latex(sym.expand(term1*term2)) ))

display( term1*term2 )
display( sym.expand(term1*term2) )
display( Math(sym.latex(sym.expand(term1*term2)) ))

x*(4*x + 5)
4*x**2 + 5*x
<IPython.core.display.Math object>


x*(4*x + 5)

4*x**2 + 5*x

<IPython.core.display.Math object>

In [7]:
term3 = x - 7 # note that parentheses are not necessary!
display(Math( sym.latex(term1*term3) ))
display(Math( sym.latex( sym.expand(term1*term3) )))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [12]:
term4 = sym.simplify(term1*term3)
display(Math(sym.latex(term4.expand())))

<IPython.core.display.Math object>

In [14]:
# with two variables
y = sym.symbols('y')
x = sym.symbols('x')

expr = x*(2*y**2 - 5**x/x)
expr_ex = sym.expand(expr)

display(Math(sym.latex(expr)))
display(Math(sym.latex(expr_ex)))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [15]:
# three expressions and three variables!!
# but first, what variables have we already created??
%whos


Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
display    function    <function display at 0x7f7fcb4eca60>
expr       Mul         x*(-5**x/x + 2*y**2)
expr_ex    Add         -5**x + 2*x*y**2
os         module      <module 'os' from '/usr/l<...>hPy/lib/python3.9/os.py'>
sym        module      <module 'sympy' from '/us<...>kages/sympy/__init__.py'>
sys        module      <module 'sys' (built-in)>
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
term4      Mul         (x - 7)*(4*x + 5)
x          Symbol      x
y          Symbol      y


In [16]:
z = sym.symbols('z')

term1 = (3 + x)
term2 = (y - 4*z)
term3 = (5/z + 3*x)

display(Math(sym.latex(term1*term2*term3)))
display(Math(sym.latex(sym.expand(term1*term2*term3))))
display(Math(sym.latex(sym.simplify(sym.expand(term1*term2*term3)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### Exercises

In [30]:
# a function of two variables
Fxy = (4+x)*(2-y)

In [29]:
val_range = range(0,3)
display(Math(sym.latex(Fxy)))
for x_i in val_range:
    for y_j in val_range:
        print('When x=%g and y=%g, f(x,y) = %g' %(x_i, y_j, Fxy.subs({x:x_i, y:y_j})))

<IPython.core.display.Math object>

When x=0 and y=0, f(x,y) = 8
When x=0 and y=1, f(x,y) = 4
When x=0 and y=2, f(x,y) = 0
When x=1 and y=0, f(x,y) = 10
When x=1 and y=1, f(x,y) = 5
When x=1 and y=2, f(x,y) = 0
When x=2 and y=0, f(x,y) = 12
When x=2 and y=1, f(x,y) = 6
When x=2 and y=2, f(x,y) = 0


In [17]:
# a function of two variables
Fxy = (4+x)*(2-y)
print(Fxy.subs({x:2,y:-2}))

24


In [28]:
numrange = range(0,3)
for i in numrange:
    for j in numrange:
        print('When x=%g and y=%g, f(x,y)=%g' %(i,j,Fxy.subs({x:i,y:j})) )

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


# VIDEO: Creating and accessing matrices with numpy

In [1]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [2]:
A = np.array( [ [1,2],[3,4] ] )
print(A)
print(type(A))
# make it look nicer
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


<IPython.core.display.Math object>

In [3]:
# initializing a matrix with zeros

numrange = range(0,5)

mat = np.zeros([len(numrange),len(numrange)])
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# populating matrices using row-col indexing

mat[0,1] = 1
mat[2,4] = 7
mat

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# can also use variables for indices
i = 2
j = 1
mat[i,j] = 4.5

display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [11]:
# now use a for-loop

numrange = range(0,4)
for row_i in numrange:
    for col_j in numrange:
        mat[row_i][col_j] = (-1)**(row_i+col_j)

mat

array([[ 1., -1.,  1., -1.,  0.],
       [-1.,  1., -1.,  1.,  0.],
       [ 1., -1.,  1., -1.,  7.],
       [-1.,  1., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### Exercise

In [12]:
from sympy.abc import x, y

In [25]:
Fxy = (4+x) * (2-y)

In [29]:
ind_mat = range(0,3)
mat = np.zeros([len(ind_mat), len(ind_mat)])
mat
for row in ind_mat:
    for col in ind_mat:
        mat[row][col] = Fxy.subs({x:row, y:col})

display(Math(sym.latex(sym.simplify(mat))))

<IPython.core.display.Math object>

In [30]:
x,y = sym.symbols('x y')
Fxy = (4+x)*(2-y)

numrange = range(0,3)

funout = np.zeros((len(numrange),len(numrange)))

for i in numrange:
    for j in numrange:
        funout[i,j] = Fxy.subs({x:i,y:j})

display(Math(sym.latex(sym.sympify(funout))))

<IPython.core.display.Math object>

### Exercise: Create a multiplication table

In [17]:
import numpy as np
import sympy as sym
from IPython.display import display, Math
mult_table = np.zeros((len(interval), len(interval)))


for col in interval:
    for line in interval:
            mult_table[col -1, line -1] = col * line


display(Math(sym.latex(sym.simplify(mult_table))))

<IPython.core.display.Math object>

In [18]:
nums = range(1,11)

multmat = np.zeros((len(nums),len(nums)),dtype=int)

for i in nums:
    for j in nums:
        multmat[i-1,j-1] = i*j

        
display(Math(sym.latex(sym.sympify(multmat)))) # no display without display

x = 3

<IPython.core.display.Math object>

# TODO: AFTER HERE
-------------------------------------------------------------------------------

# VIDEO: Associative, commutative, and distributive properties

### Associative

In [ ]:
from sympy.abc import x,y

expr1 = x*(4*y)
expr2 = (x*4)*y

# show that two equations are equal by subtracting them!
expr1 - expr2

### Commutative

In [ ]:
# create three expressions
e1 = x*4*y
e2 = 4*x*y
e3 = y*x*4

In [ ]:
# quick reminder about substitution in sympy
display( e1.subs(x,3) )

# multiple subsitutions
e3.subs({x:2,y:3})

In [ ]:
# now back to the task!
print( e1.subs({x:3,y:4}) )
print( e2.subs({x:3,y:4}) )
print( e3.subs({x:3,y:4}) )

### Distributive

In [ ]:
# another way of creating symbolic variables
from sympy.abc import a, b, c, d

expr = (a+b)*(c+d)
expr

In [ ]:
sym.expand(expr)

In [ ]:
sym.expand( (a+d)*(a-d) )

In [ ]:
# embedding expressions
a,x,y,z = sym.symbols('a,x,y,z')

x = 3*y + z
a = 4*x

display(a)

### Exercises

In [ ]:
# with these two expressions, show that the commutative rule applies

w,x,y,z = sym.symbols('w,x,y,z')

x = w*(4-w)+1/w**2*(1+w)
expr1 = x*(y+z)
expr2 = 3/x+x**2

display(Math(sym.latex(expr1*expr2)))
display(Math(sym.latex(sym.simplify(expr1*expr2))))
display(Math(sym.latex(expr2*expr1 - expr1*expr2)))


# VIDEO: Creating and working with Python lists

In [ ]:
# a list is a collection of things, and created using brackets []
# A simple example is a list of numbers

lst = [1,3,4,7]
print( lst )
print(type(lst))

In [ ]:
# you can access individual list elements
lst[2]

In [ ]:
# -1 is for the final element
lst[-1]

In [ ]:
# "slicing"

# print the first N list items
N = 2
lst[:N]


In [ ]:
# print the last k items
k = 2
lst[-k:]


In [ ]:
# print items n through k
lst = [1,2,3,4,5,6,7,8,9]

n = 3
k = 7

lst[n-1:k]


In [ ]:
# a list of strings
name = ['hello','my','name','is','Mike']

# access each element using a for-loop
for i in range(len(name)):
    print(name[i])

In [ ]:
# simpler!
for i in name:
    print(i)

In [ ]:
# lists can also hold more than one variable type
alist = [1,2,'cookies',[4,5]]

for i in alist:
    print(i)

In [ ]:
# getting items from a list-within-a-list

print( alist[-1] )

print( alist[-1][1] )

In [ ]:
# the term 'list' is reserved:
alist2 = list( (1,2,'cookies',[4,5]) )

for i in alist2:
    print(i)

In [ ]:
# importantly, we will use lists for sympy expressions!
# list_of_expressions
expr_list = [ 4*x**2 , 3+x , (1-x)/(1+x) ]

### Exercises

In [ ]:
# use sympy to expand and simplify these expressions
x = sym.symbols('x')

e1 = 2*x + x*(4-6*x) + x
e2 = -x * (2/x + 4/(x**2)) + (4+x)/(4*x)
e3 = (x + 3)*(x-3)*x*(1/(9*x))

# make a list of the expressions
exprs = [e1,e2,e3]

for i in range(0,3):
    display(Math('%s \\quad \\Longleftrightarrow \\quad %s' %(sym.latex(exprs[i]),sym.latex(sym.expand(exprs[i])))))


# VIDEO: More on "slicing" in Python

In [ ]:
# create an array (vector) of numbers
vec = [10,11,12,13,14,15,16,17,18,19,20]
# or
vec = list(range(10,21))

print(vec)

In [ ]:
# indexing a single item
vec[2]

In [ ]:
# indexing multiple items (aka slicing)
vec[2:4]

In [ ]:
# from one element to the end
vec[4:]

In [ ]:
# from the first element to a specific element
vec[:3]

In [ ]:
# the last element
vec[-1]

# penultimate element
vec[-2]


In [ ]:
# from the end to the beginning
vec[::-1]

In [ ]:
# with non-1 stepping
vec[0:5:2]

# VIDEO: Greatest common denominator

In [ ]:
# reminder: GCD is the largest integer that can divide both numbers without a remainder

# we'll use the math package for this!
import math

math.gcd(95,100)

In [ ]:
# GCD is defined for integers!
math.gcd(1,.3)

In [ ]:
math.gcd(0,3)

In [ ]:
# application: reduce fraction to lowest term

a = 16
b = 88

fact = math.gcd(a,b)

display(Math('\\frac{%g}{%g} \\quad = \\quad \\frac{%g}{%g} \\times \\frac{%g}{%g}' %(a,b,a/fact,b/fact,fact,fact)))


### Exercises

In [ ]:
# show this property using symbols, and give an example with numbers.

# gcd(m·a, m·b) = m·gcd(a, b)

a,b,c = sym.symbols('a,b,c')

display( sym.gcd(c*a,c*b) )
display( c*sym.gcd(a,b) )


# now with real numbers
a = 5
b = 6
c = 7
display( math.gcd(c*a,c*b) )
display( c*math.gcd(a,b))


In [ ]:
# double loop and store in matrix
import numpy as np

N = 10
gcdMat = np.zeros((10,15))+99

for i in range(0,10):
    for j in range(0,15):
        gcdMat[i,j] = math.gcd(i+1,j+1)
        
display(Math(sym.latex(sym.sympify(gcdMat))))

# VIDEO: Introduction to dictionaries

In [ ]:
# create a dictionary
D = dict(fruit=['banana','apple'],numbers=[1,3,4,2,5])

print(D)

In [ ]:
# list the "keys"
D.keys()

In [ ]:
# get the information from the numbers
D['numbers']

In [ ]:
# or this way
D.get('fruit')[0]

In [ ]:
len(D)

In [ ]:
# print out all information in a loop!
for items in D.keys(): # .keys() is implied!
    print(D[items])

In [ ]:
# make a dictionary of equations
x,y = sym.symbols('x,y')

D = dict(eqsWithX=[x/3-6,x*2+3],eqsWithY=[y-y/4,y-5])
D.keys()

Dkeys = list(D)

# access individual keys
D[Dkeys[0]]


### Exercise

In [ ]:
# let's make a new dictionary
x,y = sym.symbols('x,y')

# count number of x's and y's in the equation
D = dict(eqsWithX=[4*x-6,x**2-9],eqsWithY=[sym.sin(y)])

# solve them in a loop
for keyi in D:
    
    print('Equations solving for ' + keyi[-1] + ':')
    
    for i in D[keyi]:
        
        fullEQ     = sym.latex(sym.sympify(i)) + ' = 0'
        middlepart = '\\quad\\quad \\Rightarrow\\quad\\quad ' + keyi[-1] + ' = '
        soln       = sym.latex(sym.solve(i))
        
        display(Math( '\\quad\\quad ' + fullEQ + middlepart + soln ))



# VIDEO: Prime factorization

In [ ]:
# factor an integer into the product of prime numbers
number = 48

# Use the sympy function factorint. The output is a dictionary!
fact_dict = sym.factorint(number)
print(fact_dict)

In [ ]:
# just print the prime numbers
primenumbers = list( fact_dict.keys() )

print('The prime factors of ' + str(number) + ' are ' + str(primenumbers))

fact_dict[primenumbers[1]]

In [ ]:
# test on prime number
sym.factorint(4)

### Exercise

In [ ]:
# loop through numbers and report whether each number is composite or prime

nums = range(2,51)
for i in nums:
    di = sym.factorint(i)
    ks = list(di.keys())
    if len(di)==1 and di[ks[0]]==1:
        print('%s is a prime number' %i)
    else:
        print('%s is a composite number with prime factors %s' %(i,list(di.keys())))


# VIDEO: Solving inequalities

In [ ]:
x = sym.symbols('x')

expr = 4*x > 8
sym.solve(expr)

In [ ]:
display(Math(sym.latex(sym.solve(expr))))

In [ ]:
sym.oo > 10000093847529345

In [ ]:
expr = (x-1)*(x+3) > 0

display(Math(sym.latex(sym.solve(expr))))

In [ ]:
# sym.solve will return the expression if not enough information

a,b,c = sym.symbols('a,b,c')

expr = a*x > b**2/c
display(Math(sym.latex(expr)))

sym.solve(expr)#,x)

In [ ]:
# a slightly richer problem
sym.solve( 2*x**2>8 )

### Exercise

In [ ]:
expr = (3*x/2) + (4-5*x)/3 <= 2 - (5*(2-x))/4

display(Math(sym.latex(expr)))
sym.solve(expr)

# VIDEO: Adding polynomials

In [ ]:
from sympy.abc import x

# straight-forward version
p1 = 2*x**3 + x**2 - x
p2 = x**3 - x**4 - 4*x**2
print( p1+p2 )

display(Math('(%s) + (%s) \quad=\quad (%s)' %(sym.latex(p1),sym.latex(p2),sym.latex(p1+p2) )))

In [ ]:
# Using the Poly class
p1 = sym.Poly(2*x**6 + x**2 - x)

p1

In [ ]:
# can implement several methods on the polynomial object
print( p1.eval(10) )

print( p1.degree() )

In [ ]:
# create a second polynomial
p2 = sym.Poly(x**3 - x**4 - .4*x**2)
print( p1-p2 )

# can also call the add method on the polynomial objects
p1.add(p2)
p1.sub(p2)
print(p1.sub(p2))
print(p1)


### Exercise

In [ ]:
# create a list of polynomials
# loop through. if order is even, sum the coeffs. if order is odd, count the number of coeffs

polys = [ sym.Poly(2*x + x**2), sym.Poly(-x**3 + 4*x), sym.Poly(x**5-x**4+1/4*x+4) ]

for poli in polys:
    if poli.degree()%2==0:
        print('The degree of %s is even, and the coefficients sum to %s.' %(poli.as_expr(),sum(poli.coeffs())))
    else:
        print('The degree of %s is odd, and there are %s coefficients.' %(poli.as_expr(),len(poli.coeffs())))

# VIDEO: Multiplying polynomials

In [ ]:
x = sym.symbols('x')

x**2 * x**3

In [ ]:
# a litte more complicated
p1 = 4*x**2 - 2*x
p2 = x**3 + 1

p1*p2

In [ ]:
# the way your math teacher would want it written out
print( sym.expand( p1*p2 ) )

display(Math(sym.latex(p1*p2)))
display(Math(sym.latex(sym.expand(p1*p2))))


In [ ]:
# check our work from the slides!
x,y = sym.symbols('x,y')

poly1 = x**5 + 2*x*y + y**2
poly2 = x - 3*x*y

poly1*poly2

In [ ]:
display(Math(sym.latex(sym.expand( poly1*poly2 ))))

### Exercise

In [ ]:
# with x's and y's, substitute before vs after multiplication
x,y = sym.symbols('x,y')

fxy = 4*x**4 - 9*y**3 - 3*x**2 + x*y**2
gxy = 4/5*y**3 - x**3 + 6*x**2*y

display(Math( '(%s)\quad\\times\quad(%s) \quad=\quad %s' %(sym.latex(fxy),sym.latex(gxy),sym.latex(sym.expand(fxy*gxy)) )))


In [ ]:
xval = 5
yval = -2

# first substitute and then multiply
fxy_subs = fxy.subs({x:xval,y:yval})
gxy_subs = gxy.subs({x:xval,y:yval})
print('Separate substitution: %s' %(fxy_subs*gxy_subs))

# multiply then substitute
fg = (fxy*gxy).subs({x:xval,y:yval})
print('Multiplied substitution: %s' %fg)


# VIDEO: Dividing by polynomials

In [ ]:
p1 = 4*x**5 - x
p2 = 2*x**3-x

display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(p1/p2)) ))
display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(sym.expand(p1/p2))) ))
display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(sym.simplify(p1/p2))) ))


In [ ]:
# with two variables
x,y = sym.symbols('x,y')

pNum = x**3 + y**2 - 4*x**2*y + x*y + 4*y
pDen = x + y

display(Math('\\frac{%s}{%s} = %s' %(sym.latex(pNum),sym.latex(pDen),sym.latex(sym.simplify(pNum/pDen))) ))


### Exercise

In [ ]:
# first, a primer on sym.fraction

num = sym.sympify(3)/sym.sympify(4)
# num = sym.sympify(3/4)

finfo = sym.fraction(num)
print(type(finfo))
print(finfo[0])

# can also isolate the numerator separately
num = sym.fraction(num)[0]
print(num)

In [ ]:

# use a loop to find the integer value of y that makes this equation simplify
pNum = x**6 + 2*x**4 + 6*x  - y
pDen = x**3 + 3


for i in range(5,16):
    
    pnum = pNum.subs({y:i})
    display(Math('\\frac{%s}{%s} = %s' %(sym.latex(pnum),sym.latex(pDen),sym.latex(sym.simplify(pnum/pDen))) ))
    
    if sym.fraction(sym.simplify(pnum/pDen))[1]==1:
        rightnumber = i

print( 'When y=%g, there is no denominator!' %rightnumber)


# VIDEO: Factoring polynomials

In [ ]:
x,y = sym.symbols('x,y')

po = x**2 + 4*x + 3
sym.factor(po)

In [ ]:
# with output

fac = sym.factor(po)
print(fac)

In [ ]:
# not every polynomial can be factored!
po = x**2 + 4*x - 3

sym.factor(po)

In [ ]:
expr = 2*y**3 - 2*y**2 - 18*y + 18
sym.factor(expr)

In [ ]:
# multiple variables
expr = 2*x**3*y - 2*x**2*y**2 + 2*x**2*y + 6*x**2 - 6*x*y + 6*x
sym.factor(expr)


### Exercise

In [ ]:
# test whether factorable, print if so.

exprs = [ x**2+4*x+3 , 2*y**2-1 , 3*y**2+12*y ]

for expri in exprs:
    tmp = str( sym.factor(expri) )
    
    if tmp.find('(')!=-1:
        display(Math('%s \\quad\\Rightarrow\\quad %s' %(sym.latex(sym.expand(expri)),sym.latex(sym.factor(expri)))))
    else:
        display(Math('%s \\quad\\Rightarrow\\quad\\text{ not factorable!}' %sym.latex(sym.expand(expri))))
    

# VIDEO: Algebra 1 BUG HUNT!

In [ ]:
# from sympy.abc import x2
x2 = sym.symbols('x2')

x2 = 4

In [ ]:
a,b,c,d = sym.symbols('a,b,c,d')

expr = 4*b + 5*a*a - c**3 + 5*d


In [ ]:
import math
math.gcd(30,50)

In [ ]:
from sympy.abc import x

expr = 4*x - 8
sym.solve(expr)

In [ ]:
import numpy as np

A = np.array( [ [1,2],[3,4] ] )
# make it look nice
display(Math(sym.latex(sym.sympify(A))))

In [ ]:
fact_dict = sym.factorint(44)
allkeys = fact_dict.keys()

for i in fact_dict:
    print('%g was present %g times.' %(i,fact_dict[i]))


In [ ]:
x,y = sym.symbols('x,y')

expr = 4*x - 5*y**2

expr.subs({x:5})


In [ ]:
# goal is to show a fraction

f = sym.sympify(5)/9

display(Math(sym.latex(f)))


In [ ]:
# print the last 3 items from a list
lst = [1,3,2,5,4,6,7,5,3,7]
lst[-3:]


In [ ]:
from sympy.abc import x,y

expr = 2*x + 4*y

# solve for y
sym.solve(expr,y)

In [ ]:
import numpy as np

A = np.array( [ [1,2],[3,4] ] )

# set the element in the second row, second column to 9
A[1,1] = 9
print(A)