# COURSE: Master math by coding in Python
## SECTION: Algebra 1

#### https://www.udemy.com/course/math-with-python/?couponCode=MXC-DISC4ALL
#### INSTRUCTOR: sincxpress.com

Note about this code: Each video in this section of the course corresponds to a section of code below. Please note that this code roughly matches the code shown in the live recording, but is not exactly the same -- the variable names, order of lines, and parameters may be slightly different. 

In [1]:
# It's generally good practice to import all required modules at the top of the script!
import sympy as sym
import numpy as np
from IPython.display import display, Math

# VIDEO: Solving for x

In [2]:
x = sym.symbols('x')

# the expression we want to solve is 2x+4=9
expr = 2*x + 4 -9

sym.solve(expr,x)

[5/2]

In [5]:
solution = sym.solve(expr,x)
display('The solution to %s is %g' %(sym.latex(expr), solution[0]))

'The solution to 2 x - 5 is 2.5'

In [6]:
# make it look a bit nicer

sol = sym.solve(expr,x)

display('The solution to %s is %g'%(expr,sol[0]))

# or
display(Math('\\text{The solution to }%s\\text{ is x=}%g' %(sym.latex(expr),sol[0])))

'The solution to 2*x - 5 is 2.5'

<IPython.core.display.Math object>

In [5]:
# can input the equation directly into the solve function
x = sym.symbols('x')
sym.solve(x**2 - 4,x)

[-2, 2]

In [7]:
# notice the solution is stored as a list, with one solution per element
sol = sym.solve(x**2 - 4,x)

print( type(sol) )
print( len(sol) )
print(sol)

<class 'list'>
2
[-2, 2]


In [8]:
# we can print them all out:
for i in range(0,len(sol)):
    print('Solution #' + str(i+1) + ' is ' + str(sol[i]))


Solution #1 is -2
Solution #2 is 2


In [12]:
y = sym.symbols('y')

expr = x/4 - x*y + 5

print( "Solved for x: " + str(sym.solve(expr,x)[0]) )
print( "Solved for y: " + str(sym.solve(expr,y)) )

display(sym.solve(expr, x))
display(sym.solve(expr, y))


Solved for x: 20/(4*y - 1)
Solved for y: [(x + 20)/(4*x)]


[20/(4*y - 1)]

[(x + 20)/(4*x)]

### Exercises

In [2]:
import sympy as sym
from IPython.display import display, Math

In [26]:
# Ex1:
q = sym.symbols('q')
eq = (3*q) + (4/q) + 3 - (5*q) - (1/q) - 1

display(Math(sym.latex(sym.simplify(eq))))
display(Math('q=' + sym.latex(sym.solve(eq, q))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [25]:
# Ex2:
q = sym.symbols('q')
eq = 2*q + 3*(q**2) - (5 / q) - ( 4 / (q**3))
display(eq)

display(Math(sym.latex(sym.simplify(eq))))
display(Math(sym.latex(sym.cancel(eq))))
display(Math(sym.latex(sym.solve(eq))))

3*q**2 + 2*q - 5/q - 4/q**3

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [27]:
# Ex3: 
q = sym.symbols('q')
eq = (sym.sqrt(3) + sym.sqrt(15*q)) / (sym.sqrt(2) + sym.sqrt(10*q))
display(eq)
display(sym.simplify(eq))
display(eq.subs(q, 10))

(sqrt(15)*sqrt(q) + sqrt(3))/(sqrt(10)*sqrt(q) + sqrt(2))

sqrt(6)/2

(sqrt(3) + 5*sqrt(6))/(sqrt(2) + 10)

In [ ]:
# 1)
# simplify and solve for q
q = sym.symbols('q')
eq = 3*q + 4/q + 3 - 5*q - 1/q - 1

display(Math(sym.latex(eq.simplify()))) 
display(Math('q='+sym.latex(sym.solve(eq,q))))

In [ ]:
# 2)
eq = 2*q + 3*q**2 - 5/q - 4/q**3

display(Math(sym.latex(eq)))
display(Math(sym.latex(sym.simplify(eq))))
display(Math(sym.latex(sym.cancel(eq)))) # puts into p/q form with integer coefficients

In [ ]:
# 3)
# simplify this expression. confirm on your own using paper-and-pencil
expr = (sym.sqrt(3) + sym.sqrt(15)*q) / (sym.sqrt(2) + sym.sqrt(10)*q)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.simplify(expr))))

In [ ]:
sym.simplify( expr.subs(q,10) )

In [ ]:
expr.subs(q,10).evalf()

# VIDEO: Expanding terms

In [4]:
import sympy as sym
from IPython.display import display, Math

In [6]:
# define our terms
from sympy.abc import x

term1 = (4*x + 5)
term2 = x

print( term1*term2 )
print( sym.expand(term1*term2) )
print( Math(sym.latex(sym.expand(term1*term2)) ))

display( term1*term2 )
display( sym.expand(term1*term2) )
display( Math(sym.latex(sym.expand(term1*term2)) ))

x*(4*x + 5)
4*x**2 + 5*x
<IPython.core.display.Math object>


x*(4*x + 5)

4*x**2 + 5*x

<IPython.core.display.Math object>

In [7]:
term3 = x - 7 # note that parentheses are not necessary!
display(Math( sym.latex(term1*term3) ))
display(Math( sym.latex( sym.expand(term1*term3) )))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [12]:
term4 = sym.simplify(term1*term3)
display(Math(sym.latex(term4.expand())))

<IPython.core.display.Math object>

In [14]:
# with two variables
y = sym.symbols('y')
x = sym.symbols('x')

expr = x*(2*y**2 - 5**x/x)
expr_ex = sym.expand(expr)

display(Math(sym.latex(expr)))
display(Math(sym.latex(expr_ex)))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [15]:
# three expressions and three variables!!
# but first, what variables have we already created??
%whos


Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
display    function    <function display at 0x7f7fcb4eca60>
expr       Mul         x*(-5**x/x + 2*y**2)
expr_ex    Add         -5**x + 2*x*y**2
os         module      <module 'os' from '/usr/l<...>hPy/lib/python3.9/os.py'>
sym        module      <module 'sympy' from '/us<...>kages/sympy/__init__.py'>
sys        module      <module 'sys' (built-in)>
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
term4      Mul         (x - 7)*(4*x + 5)
x          Symbol      x
y          Symbol      y


In [16]:
z = sym.symbols('z')

term1 = (3 + x)
term2 = (y - 4*z)
term3 = (5/z + 3*x)

display(Math(sym.latex(term1*term2*term3)))
display(Math(sym.latex(sym.expand(term1*term2*term3))))
display(Math(sym.latex(sym.simplify(sym.expand(term1*term2*term3)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### Exercises

In [30]:
# a function of two variables
Fxy = (4+x)*(2-y)

In [29]:
val_range = range(0,3)
display(Math(sym.latex(Fxy)))
for x_i in val_range:
    for y_j in val_range:
        print('When x=%g and y=%g, f(x,y) = %g' %(x_i, y_j, Fxy.subs({x:x_i, y:y_j})))

<IPython.core.display.Math object>

When x=0 and y=0, f(x,y) = 8
When x=0 and y=1, f(x,y) = 4
When x=0 and y=2, f(x,y) = 0
When x=1 and y=0, f(x,y) = 10
When x=1 and y=1, f(x,y) = 5
When x=1 and y=2, f(x,y) = 0
When x=2 and y=0, f(x,y) = 12
When x=2 and y=1, f(x,y) = 6
When x=2 and y=2, f(x,y) = 0


In [17]:
# a function of two variables
Fxy = (4+x)*(2-y)
print(Fxy.subs({x:2,y:-2}))

24


In [28]:
numrange = range(0,3)
for i in numrange:
    for j in numrange:
        print('When x=%g and y=%g, f(x,y)=%g' %(i,j,Fxy.subs({x:i,y:j})) )

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


# VIDEO: Creating and accessing matrices with numpy

In [1]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [2]:
A = np.array( [ [1,2],[3,4] ] )
print(A)
print(type(A))
# make it look nicer
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


<IPython.core.display.Math object>

In [3]:
# initializing a matrix with zeros

numrange = range(0,5)

mat = np.zeros([len(numrange),len(numrange)])
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# populating matrices using row-col indexing

mat[0,1] = 1
mat[2,4] = 7
mat

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# can also use variables for indices
i = 2
j = 1
mat[i,j] = 4.5

display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [11]:
# now use a for-loop

numrange = range(0,4)
for row_i in numrange:
    for col_j in numrange:
        mat[row_i][col_j] = (-1)**(row_i+col_j)

mat

array([[ 1., -1.,  1., -1.,  0.],
       [-1.,  1., -1.,  1.,  0.],
       [ 1., -1.,  1., -1.,  7.],
       [-1.,  1., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### Exercise

In [12]:
from sympy.abc import x, y

In [25]:
Fxy = (4+x) * (2-y)

In [29]:
ind_mat = range(0,3)
mat = np.zeros([len(ind_mat), len(ind_mat)])
mat
for row in ind_mat:
    for col in ind_mat:
        mat[row][col] = Fxy.subs({x:row, y:col})

display(Math(sym.latex(sym.simplify(mat))))

<IPython.core.display.Math object>

In [30]:
x,y = sym.symbols('x y')
Fxy = (4+x)*(2-y)

numrange = range(0,3)

funout = np.zeros((len(numrange),len(numrange)))

for i in numrange:
    for j in numrange:
        funout[i,j] = Fxy.subs({x:i,y:j})

display(Math(sym.latex(sym.sympify(funout))))

<IPython.core.display.Math object>

### Exercise: Create a multiplication table

In [2]:
import numpy as np
import sympy as sym
from IPython.display import display, Math

interval = range(1, 11)
mult_table = np.zeros((len(interval), len(interval)))


for row in interval:
    for col in interval:
            mult_table[row -1, col -1] = row * col


display(Math(sym.latex(sym.simplify(mult_table))))

<IPython.core.display.Math object>

In [3]:
nums = range(1,11)

multmat = np.zeros((len(nums),len(nums)),dtype=int)

for i in nums:
    for j in nums:
        multmat[i-1,j-1] = i*j

        
display(Math(sym.latex(sym.sympify(multmat)))) # no display without display

x = 3

<IPython.core.display.Math object>

# VIDEO: Associative, commutative, and distributive properties

In [1]:
import sympy as sym

In [2]:
from sympy.abc import x, y

### Associative
$ a\cdot(b \times c) = (a\times b)\cdot c $ <br>
$ a\cdot(b \cdot c) = (a\cdot b)\cdot c $ <br>
$ a\cdot b \cdot c = a\cdot b\cdot c $ <br>


In [5]:
expr1 = x*(4*y)
expr2 = (x*4)*y
print(expr1 - expr2) # If the results is 0, the exprs gives the same results

0


### Commutative
$ a \times b = b\times a $ <br>
$ a\times b \times c = b\times a\times c = c\times a\times b $ <br>

In [6]:
e1 = 4*x*y
e2 = x*4*y
e3 = y*x*4

In [9]:
e1.subs(x, 3)

12*y

In [10]:
print(e1.subs({x:3, y:2}))
print(e2.subs({x:3, y:2}))
print(e3.subs({x:3, y:2}))

24
24
24


### Distributive
$ x\cdot(y + z) = x \cdot y + x \cdot z  $ <br>

In [37]:
a, b, c, d = sym.symbols('a, b, c, d')

In [38]:
expr = a*(c+d)
sym.expand(expr)

a*c + a*d

### Exercises
* Implement these expressions in Python
* Display and simplify $ f_1 \times f_2 $
* Show that the commutative property holds

$ x = w\cdot (4 - w) + \frac{1}{w^2} \cdot(1+w) $ <br>
$ f_1 = x \cdot (y + z) $ <br>

$ f_2 = \frac{3}{x} + x^2 $ <br>
$ f_3 = f_1 \times f_2 $ 

In [23]:
import sympy as sym
from IPython.display import display, Math

In [32]:
w, x, y, z = sym.symbols('w, x, y, z')


In [46]:
x = w * (4 - w) + 1/(w**2) * (1 + w)
display(Math(sym.latex(x)))
display(Math(sym.latex(x.simplify())))
display(Math(sym.latex(x.expand())))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [47]:
f1 = x * (y + z)
display(Math(sym.latex(f1)))

<IPython.core.display.Math object>

In [48]:
f2 = (3/x) + (x**2)
display(Math(sym.latex(f2)))

<IPython.core.display.Math object>

In [54]:
expr1 = f1 * f2
display(Math(sym.latex(expr1.simplify())))


<IPython.core.display.Math object>

In [55]:
# Showing that commutative property holds
expr2 = f2 * f1
display(Math(sym.latex(sym.simplify(expr1 - expr2))))

<IPython.core.display.Math object>

In [63]:
f3 = f1 * f2

In [64]:
display("Affichage de l'expression")
display(Math(sym.latex(f3)))

"Affichage de l'expression"

<IPython.core.display.Math object>

In [65]:
display("Simplification de l'expression")
display(Math(sym.latex(f3.simplify())))

"Simplification de l'expression"

<IPython.core.display.Math object>

In [66]:
display("'distribuer' l'expression")
display(Math(sym.latex(f3.expand())))

"'Etandre' l'expression"

<IPython.core.display.Math object>

# VIDEO: Creating and working with Python lists

In [8]:
lst = [1, 3, 6, 7, 2, 5, 6, 7, 8, 9, 7, 1, 0, 5, 3]
print(type(lst))

<class 'list'>


In [9]:
lst[-1]

3

In [5]:
# Slicing
N = 2
lst[:N] # From the beginning until the first N elements

[1, 3]

In [7]:
K = 2
lst[-K:] # The last K elements

[6, 7]

In [10]:
n = 3
k = 7
print(lst)
lst[n:k]

[1, 3, 6, 7, 2, 5, 6, 7, 8, 9, 7, 1, 0, 5, 3]


[7, 2, 5, 6]

In [12]:
words = ['hello', 'my', 'name', 'is', 'Adel']

for word in words:
    print(word)

for i in range(0, len(words)):
    print(words[i])

hello
my
name
is
Adel
hello
my
name
is
Adel


In [13]:
alist = [1, 2, 'cookies', [6, 4]]

for element in alist:
    print(element)

1
2
cookies
[6, 4]


In [14]:
alist[-1]

[6, 4]

In [15]:
alist[-1][0]

6

### Exercises
* Implement these expressions as a list
* Expand the expressions and print using LaTex
* Use a for loop!

$ e_1 = 2x + x \cdot (4 - 6x) + x $ <br>
$ e_2 = -x \cdot (\frac{2}{x} + \frac{4}{x^2}) + \frac{4+x}{4x} $  <br>
$ e_3 = (x + 3) \cdot (x - 3) \cdot x(\frac{1}{9x}) $


In [24]:
import sympy as sym
from IPython.display import display, Math

In [17]:
x = sym.symbols('x')

In [18]:
e1 = 2*x + x * (4-6*x) + x
display(e1)

x*(4 - 6*x) + 3*x

In [20]:
e2 = -x * (2/x + 4/(x**2)) + (4+x)/(4*x)
display(e2)

-x*(2/x + 4/x**2) + (x + 4)/(4*x)

In [21]:
e3 = (x + 3) * (x - 3) * x*(1/(9*x))
display(e3)

(x - 3)*(x + 3)/9

In [22]:
expressions = [e1, e2, e3]
display(expressions)

[x*(4 - 6*x) + 3*x, -x*(2/x + 4/x**2) + (x + 4)/(4*x), (x - 3)*(x + 3)/9]

In [31]:
for expr in expressions:
    display(Math('%s \\quad \\Longleftrightarrow \\quad %s'%(sym.latex(expr), sym.latex(expr.expand()))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

# VIDEO: More on "slicing" in Python

In [4]:
vec = list(range(10, 21))
vec

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [9]:
vec[:6]

[10, 11, 12, 13, 14, 15]

In [12]:
vec[-8]

13

In [13]:
vec[-1]

20

In [15]:
vec[::-1] # reverse the list

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]

In [16]:
#Explanation of [::]
# [A:B:C]
# A: Start of selection
# B: End of selection
# C: steps to skip, for exemple if 2, so every two index number will be skiped
# Exemple below: We just want even numbers from index 0 to 4
print(vec[0:5:2])

# We also could count in steps of 3:
print(vec[0:5:3])

[10, 12, 14]
[10, 13]


In [21]:
vec[::-2]

[20, 18, 16, 14, 12, 10]

# TODO: AFTER HERE
-------------------------------------------------------------------------------

# VIDEO: Greatest common denominator

### Exercises

# VIDEO: Introduction to dictionaries

### Exercise

# VIDEO: Prime factorization

### Exercise

# VIDEO: Solving inequalities

### Exercise

# VIDEO: Adding polynomials

### Exercise

# VIDEO: Multiplying polynomials

### Exercise

# VIDEO: Dividing by polynomials

### Exercise

# VIDEO: Factoring polynomials

### Exercise

# VIDEO: Algebra 1 BUG HUNT!